// src/constants/constants.js

export const QUOTES = [
    "Time is what we want most, but what we use worst. - William Penn",
    "The two most powerful warriors are patience and time. - Leo Tolstoy",
    "Time flies over us, but leaves its shadow behind. - Nathaniel Hawthorne",
    "Don’t count the days, make the days count. - Muhammad Ali",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "You have within you right now, everything you need to deal with whatever the world can throw at you. - Brian Tracy",
    "Time waits for no one. - Folklore",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Time is the most valuable thing a man can spend. - Theophrastus",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. - Ralph Waldo Emerson",
    "Lost time is never found again. - Benjamin Franklin",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "The best way to predict your future is to create it. - Abraham Lincoln",
    "Time is a great teacher, but unfortunately it kills all its pupils. - Louis Hector Berlioz",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "Time is a great healer, but a poor beautician. - Lucille S. Harper",
    "Our birthdays are feathers in the broad wing of time. - Jean Paul",
    "The trouble is, you think you have time. - Jack Kornfield",
    "Time is money. - Benjamin Franklin",
    "Time changes everything except something within us which is always surprised by change. - Thomas Hardy",
    "Time is an illusion. - Albert Einstein",
    "Don’t let the noise of others’ opinions drown out your own inner voice. - Steve Jobs",
    "Yesterday is history, tomorrow is a mystery, today is a gift. - Eleanor Roosevelt",
    "Life begins at the end of your comfort zone. - Neale Donald Walsch",
    "The most important thing is to enjoy your life – to be happy – it’s all that matters. - Audrey Hepburn",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "Time is a great healer, but a poor beautician. - Lucille S. Harper",
    "Time is the most valuable thing a man can spend. - Theophrastus",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "Don’t count the days, make the days count. - Muhammad Ali",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "The only impossible journey is the one you never begin. - Tony Robbins",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "Happiness is not something ready-made. It comes from your own actions. - Dalai Lama",
    "The purpose of life is to be happy. - Dalai Lama",
    "Time is a great teacher, but unfortunately it kills all its pupils. - Louis Hector Berlioz",
    "Our birthdays are feathers in the broad wing of time. - Jean Paul",
    "Time is the most valuable thing a man can spend. - Theophrastus",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "Time is what we want most, but what we use worst. - William Penn",
    "Time changes everything except something within us which is always surprised by change. - Thomas Hardy",
    "Time is a great healer, but a poor beautician. - Lucille S. Harper",
    "Yesterday is history, tomorrow is a mystery, today is a gift. - Eleanor Roosevelt",
    "Life begins at the end of your comfort zone. - Neale Donald Walsch",
    "Time is a great teacher, but unfortunately it kills all its pupils. - Louis Hector Berlioz",
    "Time is the most valuable thing a man can spend. - Theophrastus",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "Time is a great healer, but a poor beautician. - Lucille S. Harper",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "Time waits for no one. - Folklore",
    "Time is money. - Benjamin Franklin",
    "Time flies over us, but leaves its shadow behind. - Nathaniel Hawthorne",
    "Time is an illusion. - Albert Einstein",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Time changes everything except something within us which is always surprised by change. - Thomas Hardy",
    "Life is what happens when you're busy making other plans. - John Lennon",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
    "Life is what happens when you’re busy making other plans. - John Lennon",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "The trouble is, you think you have time. - Jack Kornfield",
    "Yesterday is history, tomorrow is a mystery, today is a gift. - Eleanor Roosevelt",
    "Time is an illusion. - Albert Einstein",
    "In three words I can sum up everything I’ve learned about life: It goes on. - Robert Frost",
    "Time is what we want most, but what we use worst. - William Penn",
    "Life begins at the end of your comfort zone. - Neale Donald Walsch",
    "Time waits for no one. - Folklore",
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well. - Ralph Waldo Emerson"
  ];
  